### ISSUE TITLE
[FEAT] Improve the records creation behaviour

### ISSUE THREAD

**Issue by frascuchon** [argilla-io/argilla-server#79]
A better mechanism to publish records into argilla in bulk must be implemented. The improvement should target:

- Using `external_id` as a record disambiguation, allowing users to update records based on this value. 
- Support for upsert mechanism
- Return info about created records.

The endpoint definition should be aligned with the responses bulk endpoint.

```[tasklist]
### Tasks
- [x] [TASK] Cleaning old code
- [x] [TASK] Add entity related tests
- [x] [TASK] Add new bulk endpoints for create and upsert records
```
